version: '3.9'

services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cog1
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cog1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
